version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.17-browsers
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
