version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.17-browsers
    environment:
      NODE_ENV: test
    steps:
      - checkout # check out the code in the project directory
      - run:
          command: npm install
          working_directory: src/backend
      - run:
          command: npm test
          working_directory: src/backend
